files:
  - source: /config/**/*.properties
    translation: /%locale_with_underscore%/%original_path%/%locale_with_underscore%.properties
  - source: /config/**/*.txt
    translation: /%locale_with_underscore%/%original_path%/%locale_with_underscore%.txt
  - source: /config/**/*.xml
    translation: /%locale_with_underscore%/%original_path%/InGameInfo.xml
